/* Copyright 2025 The xLLM Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/jd-opensource/xllm-service/blob/main/LICENSE

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

#pragma once

#include <absl/synchronization/mutex.h>

#include "chat_template/jinja_chat_template.h"
#include "common/types.h"
#include "common/xllm/output.h"

namespace xllm_service {

// Store request-related data
struct Request {
  // model name
  std::string model;

  // request id generated by service
  std::string service_request_id;

  // whether to stream the response
  bool stream = false;

  // whether to return usage
  bool include_usage = false;

  bool offline = false;

  // input prompt
  std::string prompt;

  // input messages
  ChatMessages messages;

  // token ids of prompt
  std::vector<int32_t> token_ids;

  // instance routing
  Routing routing;

  // the number of generated tokens
  int64_t num_generated_tokens = 0;

  // the estimated TTFT obtained from the TTFT predictor
  int64_t estimated_ttft = 0;

  // arrival timestamp (milliseconds since epoch)
  int64_t arrival_time_ms = 0;

  // TTFT SLO from request JSON (milliseconds)
  int64_t ttft_slo_ms = 0;

  // estimated prefill processing time from TimePredictor (milliseconds)
  int64_t estimated_processing_time_ms = 0;

  // output callback
  OutputCallback output_callback;

  // timeout callback, called when request is discarded due to TTFT SLO expiration
  std::function<void()> timeout_callback = nullptr;

  // trace callback
  std::function<void(const std::string&)> trace_callback = nullptr;

  // Expected absolute wall-clock time (ms since epoch) when this request's prefill
  // will complete. Set at dispatch time, used for PREFILL_DONE correction feedback.
  int64_t expected_prefill_done_ms = 0;

  // ---- Latency breakdown timestamps (ms since epoch) ----
  int64_t tokenize_done_ms = 0;    // after chat template + prompt encode
  int64_t queue_exit_ms = 0;       // popped from concurrent queue
  int64_t lb_done_ms = 0;          // after load balancing selection
  int64_t dispatch_start_ms = 0;   // dispatch_callback begins
  int64_t rpc_sent_ms = 0;         // RPC CallMethod issued to engine
  int64_t first_token_ms = 0;      // first token received (prefill done)
  int64_t finish_ms = 0;           // request completed

  // dispatch callback
  // This callback will be called in a new thread after the request is scheduled.
  std::function<void()> dispatch_callback = nullptr;

  absl::Mutex mutex;
  bool is_scheduled = false;

  // true for elastic pool requests: forces max_tokens=1 (prefill-only)
  bool prefill_only = false;

  // LstImhPolicy coordinator pre-updates metrics after assigning an instance;
  // process_request_queue checks this flag to avoid double-updating.
  bool metrics_already_updated = false;
};

}  // namespace xllm_service